/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

val mcpVersion = "0.4.0"
val slf4jVersion = "2.0.9"

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    
    // MCP 관련 의존성
    implementation("io.modelcontextprotocol:kotlin-sdk:$mcpVersion")
    implementation("org.slf4j:slf4j-nop:$slf4jVersion")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.AppKt"
}
